---
- name: add esxi host to cluster
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vcenter_hostname: vcfvcsa.lab.hpe.local
    vcenter_username: administrator@vsphere.local
    vcenter_password: M@n@g3r11!@#
    esxi_hostname: dlg7esxi01.lab.hpe.local
    esxi_username: root
    esxi_password: M@n@g3r11!@#
    datacenter_name: vcf-datacenter
    cluster_name: vcf-cluster
  tasks:
  - name: Clone a virtual machine from Windows template and customize
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}" 
      cluster: "{{ cluster_name }}"
      name: "{{ vm_name }}"
      state: poweredon
      wait_for_ip_address: yes
      template: Win10-template
      folder: danny
      networks:
      - name: vcf-vlan999-mgmt
        ip: 192.168.10.225
        netmask: 255.255.255.0
        gateway: 192.168.10.254
        # mac: aa:bb:dd:aa:00:14
        domain: lab.hpe.local
        dns_servers:
        - 192.168.10.1
        - 192.168.10.2
      - vlan: 999
        type: dhcp
      # customization:
      #  autologon: yes
      #  dns_servers:
      #  - 192.168.10.1
      #  - 192.168.10.2
      #  domain: lab.hpe.local
      #  password: new_vm_password
      #  runonce:
      #  - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
    delegate_to: localhost
